-- ============================================
-- 1. TBL_CLASS INSERT 문 수정
-- ============================================
-- 테이블 구조: CLASS_ID, CLASS_NM, DESCRIPTION, YEAR, TERM, CURRENT_INVITE_ID, USE_YN, CREATE_DT, UPDATE_DT, USER_ID, CUR_ID
-- 원본 데이터 분석: (CLASS_ID, CREATE_DT, UPDATE_DT, CLASS_NM, DESCRIPTION, CURRENT_INVITE_ID, TERM, USE_YN, YEAR, USER_ID)
-- CUR_ID가 누락되어 있으므로 추가 필요 (예: 2로 설정)

INSERT INTO `TBL_CLASS`
(`CLASS_ID`, `CLASS_NM`, `DESCRIPTION`, `YEAR`, `TERM`, `CURRENT_INVITE_ID`, `USE_YN`, `CREATE_DT`, `UPDATE_DT`, `USER_ID`, `CUR_ID`)
VALUES
    (1, 'test1', NULL, 2025, '1학기', 'test1', 1, '2025-11-04 11:02:11', '2025-11-04 11:02:11', 2, 2),
    (2, 'adfs', NULL, 2025, '2학기', 'adfs', 1, '2025-11-04 13:01:06', '2025-11-04 13:01:06', 2, 2),
    (3, 'test2', NULL, 2025, '2학기', 'test2', 1, '2025-11-04 13:11:48', '2025-11-04 13:11:48', 2, 2),
    (4, 'test2', NULL, 2025, '2학기', 'tewst2', 1, '2025-11-04 13:13:11', '2025-11-04 13:13:11', 2, 2),
    (5, 'test3', NULL, 2025, '1학기', 'test3', 1, '2025-11-04 13:33:19', '2025-11-04 13:33:19', 2, 2);

-- ============================================
-- 2. TBL_CLASS_INVITE INSERT 문 수정
-- ============================================
-- 테이블 구조: INVITE_ID, INVITE_CD, QR_CD, ACTIVE_YN, CREATE_DT, UPDATE_DT, CLASS_ID

INSERT INTO `TBL_CLASS_INVITE`
(`INVITE_ID`, `INVITE_CD`, `QR_CD`, `ACTIVE_YN`, `CREATE_DT`, `UPDATE_DT`, `CLASS_ID`)
VALUES
    (1, 'WG2DSG', '/join/WG2DSG', 1, '2025-11-04 13:11:48', '2025-11-04 13:11:48', 3),
    (2, '38XHYA', '/join/38XHYA', 1, '2025-11-04 13:13:11', '2025-11-04 13:13:11', 4),
    (3, 'ECW99V', '/join/ECW99V', 1, '2025-11-04 13:33:19', '2025-11-04 13:33:19', 5);

-- ============================================
-- 3. TBL_CURRICULUM INSERT 문 수정
-- ============================================
-- 테이블 구조: CUR_ID, LANG, NAME, DESCRIPTION, DURATION_WEEKS, USE_YN, CREATE_DT, UPDATE_DT
-- 원본 데이터 분석: (CUR_ID, CREATE_DT, UPDATE_DT, DESCRIPTION, DURATION_WEEKS, LANG, NAME, USE_YN)

INSERT INTO `TBL_CURRICULUM`
(`CUR_ID`, `LANG`, `NAME`, `DESCRIPTION`, `DURATION_WEEKS`, `USE_YN`, `CREATE_DT`, `UPDATE_DT`)
VALUES
    (1, 'Python', 'LogiCore Tech 신입 개발자 과정2', 'LogiCore Tech 신입 개발자 과정을 통해 파이썬 프로그래밍의 기초부터 실무 적용까지 단계별로 학습합니다. 각 주차별로 실습 중심의 과제를 수행하며, 변수, 자료형, 연산자, 제어문 등 핵심 개념을 익히고, 실제 업무에 활용할 수 있는 능력을 키웁니다.', 12, 0, '2025-11-03 08:46:00', '2025-11-03 08:46:00'),
    (3, 'Python', 'LogiCore Tech 신입 개발자 과정12312312', 'LogiCore Tech 신입 개발자 과정을 통해 파이썬 프로그래밍의 기초부터 실무 적용까지 단계별로 학습합니다. 각 주차별로 실습 중심의 과제를 수행하며, 변수, 자료형, 연산자, 제어문 등 핵심 개념을 익히고, 실제 업무에 활용할 수 있는 능력을 키웁니다.', 12, 0, '2025-11-03 11:25:54', '2025-11-03 11:25:54'),
    (5, 'Python', 'LogiCore Tech 신입 개발자 과정', 'LogiCore Tech 신입 개발자 과정을 통해 파이썬 프로그래밍의 기초부터 실무 적용까지 단계별로 학습합니다. 각 주차별로 실습 중심의 과제를 수행하며, 변수, 자료형, 연산자, 제어문 등 핵심 개념을 익히고, 실제 업무에 활용할 수 있는 능력을 키웁니다.', 12, 1, '2025-11-03 11:26:36', '2025-11-03 11:26:36'),
    (6, 'Python', 'LogiCore Tech 신입 개발자 과정', 'LogiCore Tech 신입 개발자 과정을 통해 파이썬 프로그래밍의 기초부터 실무 적용까지 단계별로 학습합니다. 각 주차별로 실습 중심의 과제를 수행하며, 변수, 자료형, 연산자, 제어문 등 핵심 개념을 익히고, 실제 업무에 활용할 수 있는 능력을 키웁니다.', 12, 1, '2025-11-03 11:30:23', '2025-11-03 11:30:23'),
    (7, 'Python', 'LogiCore Tech 신입 개발자 과정', 'LogiCore Tech 신입 개발자 과정을 통해 파이썬 프로그래밍의 기초부터 실무 적용까지 단계별로 학습합니다. 각 주차별로 실습 중심의 과제를 수행하며, 변수, 자료형, 연산자, 제어문 등 핵심 개념을 익히고, 실제 업무에 활용할 수 있는 능력을 키웁니다.', 12, 1, '2025-11-03 15:59:33', '2025-11-03 15:59:33');

-- ============================================
-- 4. TBL_CURRICULUM_WEEK INSERT 문 수정
-- ============================================
-- 테이블 구조: CUR_ID, WEEK_NO, TITLE, SUBTITLE, CONTENT, CUR_LEV, CHARACTER_NM, CREATE_DT
-- 원본 데이터 분석: (WEEK_NO, CHARACTER_NM, CONTENT, CREATE_DT, CUR_LEV, SUBTITLE, TITLE, CUR_ID)

INSERT INTO `TBL_CURRICULUM_WEEK`
(`CUR_ID`, `WEEK_NO`, `TITLE`, `SUBTITLE`, `CONTENT`, `CUR_LEV`, `CHARACTER_NM`, `CREATE_DT`)
VALUES
    (1, 1, '팀장 과업 지시', '첫 코드 작성과 데이터 저장', '${userName}님, 환영합니다! 개발자로서의 첫 임무는 간단합니다. 화면에 <span class=\'font-bold text-yellow-300\'>\"Welcome to LogiCore Tech!\"</span> 라는 환영 메시지를 출력하는 파이썬 코드를 작성해주세요. 개발 환경은 이미 준비되어 있습니다.', 1, 'profKim', '2025-11-03 08:46:00'),
    (1, 2, '팀장 과업 지시', '데이터 가공하기: 연산자와 문자열', '기획팀에서 간단한 데이터 분석을 요청했습니다. 어제 하루 동안의 <span class=\'font-bold text-yellow-300\'>총 방문자 수(total_visits)가 1,250명</span>이고, <span class=\'font-bold text-yellow-300\'>유료 전환 사용자(paid_users)가 50명</span>일 때, \'유료 전환율(conversion_rate)\'이 몇 퍼센트인지 계산해서 출력해주세요.', 1, 'profKim', '2025-11-03 08:46:00'),
    (1, 3, '팀장 과업 지시', '흐름 제어: 조건과 반복으로 똑똑한 코드 만들기', '보안 강화의 첫 단계입니다. `user_role` 변수의 값에 따라 다른 환영 메시지를 보여주는 기능을 구현해야 합니다. 역할이 <span class=\'font-bold text-yellow-300\'>\'admin\'이면 \'관리자님 환영합니다.\'</span>를, <span class=\'font-bold text-yellow-300\'>\'editor\'이면 \'에디터님 안녕하세요.\'</span>를, 그 외의 <span class=\'font-bold text-yellow-300\'>모든 경우에는 \'환영합니다.\'</span>를 출력해주세요.', 1, 'profKim', '2025-11-03 08:46:00'),
    (1, 4, '팀장 과업 지시', '코드 재사용의 시작: 함수 정의와 활용', '여러 곳에서 사용될 환영 메시지를 매번 복사 붙여넣기 하는 대신, <span class=\'font-bold text-yellow-300\'>재사용 가능한 코드 덩어리</span>로 만들려고 합니다. \"Welcome to LogiCore Tech!\"를 출력하는 <span class=\'font-bold text-yellow-300\'>`show_welcome_message` 함수를 정의하고, 이 함수를 호출</span>해주세요.', 1, 'profKim', '2025-11-03 08:46:00'),
    (1, 5, '팀장 과업 지시', '자료구조 (1): 순서가 있는 데이터 묶음, 리스트와 튜플', '다음 스프린트에서 진행할 업무 목록을 관리해야 합니다. 먼저 <span class=\'font-bold text-yellow-300\'>`sprint_tasks` 라는 이름의 비어있는 리스트</span>를 하나 만들어주세요. 그 다음, 목록에 <span class=\'font-bold text-yellow-300\'>\'사용자 로그인 기능 개발\'</span>과 <span class=\'font-bold text-yellow-300\'>\'게시판 UI 개선\'</span>이라는 두 가지 업무를 추가해주세요.', 1, 'profKim', '2025-11-03 08:46:00'),
    (1, 6, '팀장 과업 지시', '자료구조 (2): Key-Value 데이터, 딕셔너리와 집합', '지금까지 사용자 정보를 개별 변수로 관리했는데, 한계가 명확하네요. <span class=\'font-bold text-yellow-300\'>한 명의 사용자 프로필 정보</span>(\'username\': \'rookie\', \'level\': 1, \'team\': \'솔루션개발팀\')를 하나의 묶음으로 관리해야 합니다. **\'딕셔너리(Dictionary)\'**를 사용하여 이 정보를 담은 `user_profile` 변수를 만들어주세요.', 1, 'profKim', '2025-11-03 08:46:00'),
    (1, 7, '팀장 과업 지시', '모듈화 및 중간 점검: 나만의 유틸리티 모듈 만들기', '다른 파일(`string_utils.py`)에 문자열을 뒤집는 `reverse_string` 함수가 정의되어 있다고 가정합니다. 현재 파일에서 <span class=\'font-bold text-yellow-300\'>`string_utils` 모듈을 불러오고(import)</span>, 이 모듈의 <span class=\'font-bold text-yellow-300\'>`reverse_string` 함수를 호출</span>하여 \"Hello\" 문자열을 뒤집은 결과를 `reversed_text` 변수에 저장해주세요.', 1, 'profKim', '2025-11-03 08:46:00'),
    (1, 8, '팀장 과업 지시', '객체 지향 프로그래밍 (1): 클래스와 객체의 이해', '사용자 데이터를 보다 체계적으로 관리하기 위해 <span class=\'font-bold text-yellow-300\'>\'객체 지향 프로그래밍\'</span> 개념을 도입하려고 합니다. 먼저, 사용자를 나타내는 설계도인 <span class=\'font-bold text-yellow-300\'>`User` 클래스를 정의</span>하고, 이 설계도를 바탕으로 실제 사용자 객체 <span class=\'font-bold text-yellow-300\'>`user1`을 생성</span>해주세요. 지금은 빈 껍데기만 만들어도 됩니다.', 1, 'profKim', '2025-11-03 08:46:00'),
    (1, 9, '팀장 과업 지시', '객체 지향 프로그래밍 (2): 상속을 통한 코드 확장', '서비스에 특별 권한을 가진 \'관리자\'가 필요하게 되었습니다. 관리자는 \'사용자\'의 속성(이름, 이메일)을 그대로 가지면서, 추가로 <span class=\'font-bold text-yellow-300\'>\'관리 등급(admin_level)\'</span> 속성을 가져야 합니다. <span class=\'font-bold text-yellow-300\'>상속(Inheritance)</span>을 사용하여 `User` 클래스를 확장한 `Admin` 클래스를 만들어주세요.', 1, 'profKim', '2025-11-03 08:46:00'),
    (1, 10, '팀장 과업 지시', '파일 처리와 예외 관리: 데이터 영구 저장 및 오류 대응', '서버 이벤트를 파일에 기록해야 합니다. <span class=\'font-bold text-yellow-300\'>`log_message` 내용을 `server.log` 파일에 새로 쓰는(write)</span> 코드를 작성해주세요. 그리고 기록 확인을 위해, <span class=\'font-bold text-yellow-300\'>파일 전체 내용을 다시 읽어서(read)</span> `content` 변수에 저장해야 합니다. <span class=\'font-bold text-yellow-300\'>`with open()` 구문</span>을 사용하세요.', 1, 'profKim', '2025-11-03 08:46:00'),
    (1, 11, '팀장 과업 지시', '파이썬 생태계 첫걸음: 표준 라이브러리와 외부 패키지', '이전 백업 스크립트의 의존성 문제를 해결하기 위해, 파이썬 <span class=\'font-bold text-yellow-300\'>표준 라이브러리 `zipfile`</span>을 사용하도록 코드를 개선합니다. <span class=\'font-bold text-yellow-300\'>`zipfile.ZipFile`</span>을 사용하여 `backup.zip` 파일을 열고, `important_data.txt` 파일을 이 <span class=\'font-bold text-yellow-300\'>ZIP 아카이브에 추가</span>하는 코드를 작성해주세요. `with` 구문을 사용해야 합니다.', 1, 'profKim', '2025-11-03 08:46:00'),
    (1, 12, '팀장 과업 지시', '최종 프로젝트: 주소록 관리 프로그램 제작', '마지막 과제입니다! <span class=\'font-bold text-yellow-300\'>연락처를 추가하고 볼 수 있는</span> 간단한 \'명령줄 주소록 프로그램\'을 만들려고 합니다. 이번 단계에서는 코딩 대신, 이 프로그램의 <span class=\'font-bold text-yellow-300\'>기능 목록, 데이터 저장 방식(클래스/변수 구조), 데이터 영속성(파일 저장) 방안, 사용자 인터페이스 흐름</span> 등을 포함한 구체적인 \'설계\' 문서를 작성해주세요.', 1, 'profKim', '2025-11-03 08:46:00'),
    (3, 1, '팀장 과업 지시', '첫 코드 작성과 데이터 저장', '${userName}님, 환영합니다! 개발자로서의 첫 임무는 간단합니다. 화면에 <span class=\'font-bold text-yellow-300\'>\"Welcome to LogiCore Tech!\"</span> 라는 환영 메시지를 출력하는 파이썬 코드를 작성해주세요. 개발 환경은 이미 준비되어 있습니다.', 1, 'profKim', '2025-11-03 11:25:54'),
    (3, 2, '팀장 과업 지시', '데이터 가공하기: 연산자와 문자열', '기획팀에서 간단한 데이터 분석을 요청했습니다. 어제 하루 동안의 <span class=\'font-bold text-yellow-300\'>총 방문자 수(total_visits)가 1,250명</span>이고, <span class=\'font-bold text-yellow-300\'>유료 전환 사용자(paid_users)가 50명</span>일 때, \'유료 전환율(conversion_rate)\'이 몇 퍼센트인지 계산해서 출력해주세요.', 1, 'profKim', '2025-11-03 11:25:54'),
    (3, 3, '팀장 과업 지시', '흐름 제어: 조건과 반복으로 똑똑한 코드 만들기', '보안 강화의 첫 단계입니다. `user_role` 변수의 값에 따라 다른 환영 메시지를 보여주는 기능을 구현해야 합니다. 역할이 <span class=\'font-bold text-yellow-300\'>\'admin\'이면 \'관리자님 환영합니다.\'</span>를, <span class=\'font-bold text-yellow-300\'>\'editor\'이면 \'에디터님 안녕하세요.\'</span>를, 그 외의 <span class=\'font-bold text-yellow-300\'>모든 경우에는 \'환영합니다.\'</span>를 출력해주세요.', 1, 'profKim', '2025-11-03 11:25:54'),
    (3, 4, '팀장 과업 지시', '코드 재사용의 시작: 함수 정의와 활용', '여러 곳에서 사용될 환영 메시지를 매번 복사 붙여넣기 하는 대신, <span class=\'font-bold text-yellow-300\'>재사용 가능한 코드 덩어리</span>로 만들려고 합니다. \"Welcome to LogiCore Tech!\"를 출력하는 <span class=\'font-bold text-yellow-300\'>`show_welcome_message` 함수를 정의하고, 이 함수를 호출</span>해주세요.', 1, 'profKim', '2025-11-03 11:25:54'),
    (3, 5, '팀장 과업 지시', '자료구조 (1): 순서가 있는 데이터 묶음, 리스트와 튜플', '다음 스프린트에서 진행할 업무 목록을 관리해야 합니다. 먼저 <span class=\'font-bold text-yellow-300\'>`sprint_tasks` 라는 이름의 비어있는 리스트</span>를 하나 만들어주세요. 그 다음, 목록에 <span class=\'font-bold text-yellow-300\'>\'사용자 로그인 기능 개발\'</span>과 <span class=\'font-bold text-yellow-300\'>\'게시판 UI 개선\'</span>이라는 두 가지 업무를 추가해주세요.', 1, 'profKim', '2025-11-03 11:25:54'),
    (3, 6, '팀장 과업 지시', '자료구조 (2): Key-Value 데이터, 딕셔너리와 집합', '지금까지 사용자 정보를 개별 변수로 관리했는데, 한계가 명확하네요. <span class=\'font-bold text-yellow-300\'>한 명의 사용자 프로필 정보</span>(\'username\': \'rookie\', \'level\': 1, \'team\': \'솔루션개발팀\')를 하나의 묶음으로 관리해야 합니다. **\'딕셔너리(Dictionary)\'**를 사용하여 이 정보를 담은 `user_profile` 변수를 만들어주세요.', 1, 'profKim', '2025-11-03 11:25:54'),
    (3, 7, '팀장 과업 지시', '모듈화 및 중간 점검: 나만의 유틸리티 모듈 만들기', '다른 파일(`string_utils.py`)에 문자열을 뒤집는 `reverse_string` 함수가 정의되어 있다고 가정합니다. 현재 파일에서 <span class=\'font-bold text-yellow-300\'>`string_utils` 모듈을 불러오고(import)</span>, 이 모듈의 <span class=\'font-bold text-yellow-300\'>`reverse_string` 함수를 호출</span>하여 \"Hello\" 문자열을 뒤집은 결과를 `reversed_text` 변수에 저장해주세요.', 1, 'profKim', '2025-11-03 11:25:54'),
    (3, 8, '팀장 과업 지시', '객체 지향 프로그래밍 (1): 클래스와 객체의 이해', '사용자 데이터를 보다 체계적으로 관리하기 위해 <span class=\'font-bold text-yellow-300\'>\'객체 지향 프로그래밍\'</span> 개념을 도입하려고 합니다. 먼저, 사용자를 나타내는 설계도인 <span class=\'font-bold text-yellow-300\'>`User` 클래스를 정의</span>하고, 이 설계도를 바탕으로 실제 사용자 객체 <span class=\'font-bold text-yellow-300\'>`user1`을 생성</span>해주세요. 지금은 빈 껍데기만 만들어도 됩니다.', 1, 'profKim', '2025-11-03 11:25:54'),
    (3, 9, '팀장 과업 지시', '객체 지향 프로그래밍 (2): 상속을 통한 코드 확장', '서비스에 특별 권한을 가진 \'관리자\'가 필요하게 되었습니다. 관리자는 \'사용자\'의 속성(이름, 이메일)을 그대로 가지면서, 추가로 <span class=\'font-bold text-yellow-300\'>\'관리 등급(admin_level)\'</span> 속성을 가져야 합니다. <span class=\'font-bold text-yellow-300\'>상속(Inheritance)</span>을 사용하여 `User` 클래스를 확장한 `Admin` 클래스를 만들어주세요.', 1, 'profKim', '2025-11-03 11:25:54'),
    (3, 10, '팀장 과업 지시', '파일 처리와 예외 관리: 데이터 영구 저장 및 오류 대응', '서버 이벤트를 파일에 기록해야 합니다. <span class=\'font-bold text-yellow-300\'>`log_message` 내용을 `server.log` 파일에 새로 쓰는(write)</span> 코드를 작성해주세요. 그리고 기록 확인을 위해, <span class=\'font-bold text-yellow-300\'>파일 전체 내용을 다시 읽어서(read)</span> `content` 변수에 저장해야 합니다. <span class=\'font-bold text-yellow-300\'>`with open()` 구문</span>을 사용하세요.', 1, 'profKim', '2025-11-03 11:25:54'),
    (3, 11, '팀장 과업 지시', '파이썬 생태계 첫걸음: 표준 라이브러리와 외부 패키지', '이전 백업 스크립트의 의존성 문제를 해결하기 위해, 파이썬 <span class=\'font-bold text-yellow-300\'>표준 라이브러리 `zipfile`</span>을 사용하도록 코드를 개선합니다. <span class=\'font-bold text-yellow-300\'>`zipfile.ZipFile`</span>을 사용하여 `backup.zip` 파일을 열고, `important_data.txt` 파일을 이 <span class=\'font-bold text-yellow-300\'>ZIP 아카이브에 추가</span>하는 코드를 작성해주세요. `with` 구문을 사용해야 합니다.', 1, 'profKim', '2025-11-03 11:25:54'),
    (3, 12, '팀장 과업 지시', '최종 프로젝트: 주소록 관리 프로그램 제작', '마지막 과제입니다! <span class=\'font-bold text-yellow-300\'>연락처를 추가하고 볼 수 있는</span> 간단한 \'명령줄 주소록 프로그램\'을 만들려고 합니다. 이번 단계에서는 코딩 대신, 이 프로그램의 <span class=\'font-bold text-yellow-300\'>기능 목록, 데이터 저장 방식(클래스/변수 구조), 데이터 영속성(파일 저장) 방안, 사용자 인터페이스 흐름</span> 등을 포함한 구체적인 \'설계\' 문서를 작성해주세요.', 1, 'profKim', '2025-11-03 11:25:54'),
    (5, 1, '팀장 과업 지시', '첫 코드 작성과 데이터 저장', '${userName}님, 환영합니다! 개발자로서의 첫 임무는 간단합니다. 화면에 <span class=\'font-bold text-yellow-300\'>\"Welcome to LogiCore Tech!\"</span> 라는 환영 메시지를 출력하는 파이썬 코드를 작성해주세요. 개발 환경은 이미 준비되어 있습니다.', 1, 'profKim', '2025-11-03 11:26:36'),
    (5, 2, '팀장 과업 지시', '데이터 가공하기: 연산자와 문자열', '기획팀에서 간단한 데이터 분석을 요청했습니다. 어제 하루 동안의 <span class=\'font-bold text-yellow-300\'>총 방문자 수(total_visits)가 1,250명</span>이고, <span class=\'font-bold text-yellow-300\'>유료 전환 사용자(paid_users)가 50명</span>일 때, \'유료 전환율(conversion_rate)\'이 몇 퍼센트인지 계산해서 출력해주세요.', 1, 'profKim', '2025-11-03 11:26:36'),
    (5, 3, '팀장 과업 지시', '흐름 제어: 조건과 반복으로 똑똑한 코드 만들기', '보안 강화의 첫 단계입니다. `user_role` 변수의 값에 따라 다른 환영 메시지를 보여주는 기능을 구현해야 합니다. 역할이 <span class=\'font-bold text-yellow-300\'>\'admin\'이면 \'관리자님 환영합니다.\'</span>를, <span class=\'font-bold text-yellow-300\'>\'editor\'이면 \'에디터님 안녕하세요.\'</span>를, 그 외의 <span class=\'font-bold text-yellow-300\'>모든 경우에는 \'환영합니다.\'</span>를 출력해주세요.', 1, 'profKim', '2025-11-03 11:26:36'),
    (5, 4, '팀장 과업 지시', '코드 재사용의 시작: 함수 정의와 활용', '여러 곳에서 사용될 환영 메시지를 매번 복사 붙여넣기 하는 대신, <span class=\'font-bold text-yellow-300\'>재사용 가능한 코드 덩어리</span>로 만들려고 합니다. \"Welcome to LogiCore Tech!\"를 출력하는 <span class=\'font-bold text-yellow-300\'>`show_welcome_message` 함수를 정의하고, 이 함수를 호출</span>해주세요.', 1, 'profKim', '2025-11-03 11:26:36'),
    (5, 5, '팀장 과업 지시', '자료구조 (1): 순서가 있는 데이터 묶음, 리스트와 튜플', '다음 스프린트에서 진행할 업무 목록을 관리해야 합니다. 먼저 <span class=\'font-bold text-yellow-300\'>`sprint_tasks` 라는 이름의 비어있는 리스트</span>를 하나 만들어주세요. 그 다음, 목록에 <span class=\'font-bold text-yellow-300\'>\'사용자 로그인 기능 개발\'</span>과 <span class=\'font-bold text-yellow-300\'>\'게시판 UI 개선\'</span>이라는 두 가지 업무를 추가해주세요.', 1, 'profKim', '2025-11-03 11:26:36'),
    (5, 6, '팀장 과업 지시', '자료구조 (2): Key-Value 데이터, 딕셔너리와 집합', '지금까지 사용자 정보를 개별 변수로 관리했는데, 한계가 명확하네요. <span class=\'font-bold text-yellow-300\'>한 명의 사용자 프로필 정보</span>(\'username\': \'rookie\', \'level\': 1, \'team\': \'솔루션개발팀\')를 하나의 묶음으로 관리해야 합니다. **\'딕셔너리(Dictionary)\'**를 사용하여 이 정보를 담은 `user_profile` 변수를 만들어주세요.', 1, 'profKim', '2025-11-03 11:26:36'),
    (5, 7, '팀장 과업 지시', '모듈화 및 중간 점검: 나만의 유틸리티 모듈 만들기', '다른 파일(`string_utils.py`)에 문자열을 뒤집는 `reverse_string` 함수가 정의되어 있다고 가정합니다. 현재 파일에서 <span class=\'font-bold text-yellow-300\'>`string_utils` 모듈을 불러오고(import)</span>, 이 모듈의 <span class=\'font-bold text-yellow-300\'>`reverse_string` 함수를 호출</span>하여 \"Hello\" 문자열을 뒤집은 결과를 `reversed_text` 변수에 저장해주세요.', 1, 'profKim', '2025-11-03 11:26:36'),
    (5, 8, '팀장 과업 지시', '객체 지향 프로그래밍 (1): 클래스와 객체의 이해', '사용자 데이터를 보다 체계적으로 관리하기 위해 <span class=\'font-bold text-yellow-300\'>\'객체 지향 프로그래밍\'</span> 개념을 도입하려고 합니다. 먼저, 사용자를 나타내는 설계도인 <span class=\'font-bold text-yellow-300\'>`User` 클래스를 정의</span>하고, 이 설계도를 바탕으로 실제 사용자 객체 <span class=\'font-bold text-yellow-300\'>`user1`을 생성</span>해주세요. 지금은 빈 껍데기만 만들어도 됩니다.', 1, 'profKim', '2025-11-03 11:26:36'),
    (5, 9, '팀장 과업 지시', '객체 지향 프로그래밍 (2): 상속을 통한 코드 확장', '서비스에 특별 권한을 가진 \'관리자\'가 필요하게 되었습니다. 관리자는 \'사용자\'의 속성(이름, 이메일)을 그대로 가지면서, 추가로 <span class=\'font-bold text-yellow-300\'>\'관리 등급(admin_level)\'</span> 속성을 가져야 합니다. <span class=\'font-bold text-yellow-300\'>상속(Inheritance)</span>을 사용하여 `User` 클래스를 확장한 `Admin` 클래스를 만들어주세요.', 1, 'profKim', '2025-11-03 11:26:36'),
    (5, 10, '팀장 과업 지시', '파일 처리와 예외 관리: 데이터 영구 저장 및 오류 대응', '서버 이벤트를 파일에 기록해야 합니다. <span class=\'font-bold text-yellow-300\'>`log_message` 내용을 `server.log` 파일에 새로 쓰는(write)</span> 코드를 작성해주세요. 그리고 기록 확인을 위해, <span class=\'font-bold text-yellow-300\'>파일 전체 내용을 다시 읽어서(read)</span> `content` 변수에 저장해야 합니다. <span class=\'font-bold text-yellow-300\'>`with open()` 구문</span>을 사용하세요.', 1, 'profKim', '2025-11-03 11:26:36'),
    (5, 11, '팀장 과업 지시', '파이썬 생태계 첫걸음: 표준 라이브러리와 외부 패키지', '이전 백업 스크립트의 의존성 문제를 해결하기 위해, 파이썬 <span class=\'font-bold text-yellow-300\'>표준 라이브러리 `zipfile`</span>을 사용하도록 코드를 개선합니다. <span class=\'font-bold text-yellow-300\'>`zipfile.ZipFile`</span>을 사용하여 `backup.zip` 파일을 열고, `important_data.txt` 파일을 이 <span class=\'font-bold text-yellow-300\'>ZIP 아카이브에 추가</span>하는 코드를 작성해주세요. `with` 구문을 사용해야 합니다.', 1, 'profKim', '2025-11-03 11:26:36'),
    (5, 12, '팀장 과업 지시', '최종 프로젝트: 주소록 관리 프로그램 제작', '마지막 과제입니다! <span class=\'font-bold text-yellow-300\'>연락처를 추가하고 볼 수 있는</span> 간단한 \'명령줄 주소록 프로그램\'을 만들려고 합니다. 이번 단계에서는 코딩 대신, 이 프로그램의 <span class=\'font-bold text-yellow-300\'>기능 목록, 데이터 저장 방식(클래스/변수 구조), 데이터 영속성(파일 저장) 방안, 사용자 인터페이스 흐름</span> 등을 포함한 구체적인 \'설계\' 문서를 작성해주세요.', 1, 'profKim', '2025-11-03 11:26:36'),
    (6, 1, '팀장 과업 지시', '첫 코드 작성과 데이터 저장', '${userName}님, 환영합니다! 개발자로서의 첫 임무는 간단합니다. 화면에 <span class=\'font-bold text-yellow-300\'>\"Welcome to LogiCore Tech!\"</span> 라는 환영 메시지를 출력하는 파이썬 코드를 작성해주세요. 개발 환경은 이미 준비되어 있습니다.', 1, 'profKim', '2025-11-03 11:30:23'),
    (6, 2, '팀장 과업 지시', '데이터 가공하기: 연산자와 문자열', '기획팀에서 간단한 데이터 분석을 요청했습니다. 어제 하루 동안의 <span class=\'font-bold text-yellow-300\'>총 방문자 수(total_visits)가 1,250명</span>이고, <span class=\'font-bold text-yellow-300\'>유료 전환 사용자(paid_users)가 50명</span>일 때, \'유료 전환율(conversion_rate)\'이 몇 퍼센트인지 계산해서 출력해주세요.', 1, 'profKim', '2025-11-03 11:30:23'),
    (6, 3, '팀장 과업 지시', '흐름 제어: 조건과 반복으로 똑똑한 코드 만들기', '보안 강화의 첫 단계입니다. `user_role` 변수의 값에 따라 다른 환영 메시지를 보여주는 기능을 구현해야 합니다. 역할이 <span class=\'font-bold text-yellow-300\'>\'admin\'이면 \'관리자님 환영합니다.\'</span>를, <span class=\'font-bold text-yellow-300\'>\'editor\'이면 \'에디터님 안녕하세요.\'</span>를, 그 외의 <span class=\'font-bold text-yellow-300\'>모든 경우에는 \'환영합니다.\'</span>를 출력해주세요.', 1, 'profKim', '2025-11-03 11:30:23'),
    (6, 4, '팀장 과업 지시', '코드 재사용의 시작: 함수 정의와 활용', '여러 곳에서 사용될 환영 메시지를 매번 복사 붙여넣기 하는 대신, <span class=\'font-bold text-yellow-300\'>재사용 가능한 코드 덩어리</span>로 만들려고 합니다. \"Welcome to LogiCore Tech!\"를 출력하는 <span class=\'font-bold text-yellow-300\'>`show_welcome_message` 함수를 정의하고, 이 함수를 호출</span>해주세요.', 1, 'profKim', '2025-11-03 11:30:23'),
    (6, 5, '팀장 과업 지시', '자료구조 (1): 순서가 있는 데이터 묶음, 리스트와 튜플', '다음 스프린트에서 진행할 업무 목록을 관리해야 합니다. 먼저 <span class=\'font-bold text-yellow-300\'>`sprint_tasks` 라는 이름의 비어있는 리스트</span>를 하나 만들어주세요. 그 다음, 목록에 <span class=\'font-bold text-yellow-300\'>\'사용자 로그인 기능 개발\'</span>과 <span class=\'font-bold text-yellow-300\'>\'게시판 UI 개선\'</span>이라는 두 가지 업무를 추가해주세요.', 1, 'profKim', '2025-11-03 11:30:23'),
    (6, 6, '팀장 과업 지시', '자료구조 (2): Key-Value 데이터, 딕셔너리와 집합', '지금까지 사용자 정보를 개별 변수로 관리했는데, 한계가 명확하네요. <span class=\'font-bold text-yellow-300\'>한 명의 사용자 프로필 정보</span>(\'username\': \'rookie\', \'level\': 1, \'team\': \'솔루션개발팀\')를 하나의 묶음으로 관리해야 합니다. **\'딕셔너리(Dictionary)\'**를 사용하여 이 정보를 담은 `user_profile` 변수를 만들어주세요.', 1, 'profKim', '2025-11-03 11:30:23'),
    (6, 7, '팀장 과업 지시', '모듈화 및 중간 점검: 나만의 유틸리티 모듈 만들기', '다른 파일(`string_utils.py`)에 문자열을 뒤집는 `reverse_string` 함수가 정의되어 있다고 가정합니다. 현재 파일에서 <span class=\'font-bold text-yellow-300\'>`string_utils` 모듈을 불러오고(import)</span>, 이 모듈의 <span class=\'font-bold text-yellow-300\'>`reverse_string` 함수를 호출</span>하여 \"Hello\" 문자열을 뒤집은 결과를 `reversed_text` 변수에 저장해주세요.', 1, 'profKim', '2025-11-03 11:30:23'),
    (6, 8, '팀장 과업 지시', '객체 지향 프로그래밍 (1): 클래스와 객체의 이해', '사용자 데이터를 보다 체계적으로 관리하기 위해 <span class=\'font-bold text-yellow-300\'>\'객체 지향 프로그래밍\'</span> 개념을 도입하려고 합니다. 먼저, 사용자를 나타내는 설계도인 <span class=\'font-bold text-yellow-300\'>`User` 클래스를 정의</span>하고, 이 설계도를 바탕으로 실제 사용자 객체 <span class=\'font-bold text-yellow-300\'>`user1`을 생성</span>해주세요. 지금은 빈 껍데기만 만들어도 됩니다.', 1, 'profKim', '2025-11-03 11:30:23'),
    (6, 9, '팀장 과업 지시', '객체 지향 프로그래밍 (2): 상속을 통한 코드 확장', '서비스에 특별 권한을 가진 \'관리자\'가 필요하게 되었습니다. 관리자는 \'사용자\'의 속성(이름, 이메일)을 그대로 가지면서, 추가로 <span class=\'font-bold text-yellow-300\'>\'관리 등급(admin_level)\'</span> 속성을 가져야 합니다. <span class=\'font-bold text-yellow-300\'>상속(Inheritance)</span>을 사용하여 `User` 클래스를 확장한 `Admin` 클래스를 만들어주세요.', 1, 'profKim', '2025-11-03 11:30:23'),
    (6, 10, '팀장 과업 지시', '파일 처리와 예외 관리: 데이터 영구 저장 및 오류 대응', '서버 이벤트를 파일에 기록해야 합니다. <span class=\'font-bold text-yellow-300\'>`log_message` 내용을 `server.log` 파일에 새로 쓰는(write)</span> 코드를 작성해주세요. 그리고 기록 확인을 위해, <span class=\'font-bold text-yellow-300\'>파일 전체 내용을 다시 읽어서(read)</span> `content` 변수에 저장해야 합니다. <span class=\'font-bold text-yellow-300\'>`with open()` 구문</span>을 사용하세요.', 1, 'profKim', '2025-11-03 11:30:23'),
    (6, 11, '팀장 과업 지시', '파이썬 생태계 첫걸음: 표준 라이브러리와 외부 패키지', '이전 백업 스크립트의 의존성 문제를 해결하기 위해, 파이썬 <span class=\'font-bold text-yellow-300\'>표준 라이브러리 `zipfile`</span>을 사용하도록 코드를 개선합니다. <span class=\'font-bold text-yellow-300\'>`zipfile.ZipFile`</span>을 사용하여 `backup.zip` 파일을 열고, `important_data.txt` 파일을 이 <span class=\'font-bold text-yellow-300\'>ZIP 아카이브에 추가</span>하는 코드를 작성해주세요. `with` 구문을 사용해야 합니다.', 1, 'profKim', '2025-11-03 11:30:23'),
    (6, 12, '팀장 과업 지시', '최종 프로젝트: 주소록 관리 프로그램 제작', '마지막 과제입니다! <span class=\'font-bold text-yellow-300\'>연락처를 추가하고 볼 수 있는</span> 간단한 \'명령줄 주소록 프로그램\'을 만들려고 합니다. 이번 단계에서는 코딩 대신, 이 프로그램의 <span class=\'font-bold text-yellow-300\'>기능 목록, 데이터 저장 방식(클래스/변수 구조), 데이터 영속성(파일 저장) 방안, 사용자 인터페이스 흐름</span> 등을 포함한 구체적인 \'설계\' 문서를 작성해주세요.', 1, 'profKim', '2025-11-03 11:30:23'),
    (7, 1, '팀장 과업 지시', '첫 코드 작성과 데이터 저장', '${userName}님, 환영합니다! 개발자로서의 첫 임무는 간단합니다. 화면에 <span class=\'font-bold text-yellow-300\'>\"Welcome to LogiCore Tech!\"</span> 라는 환영 메시지를 출력하는 파이썬 코드를 작성해주세요. 개발 환경은 이미 준비되어 있습니다.', 1, 'profKim', '2025-11-03 15:59:33'),
    (7, 2, '팀장 과업 지시', '데이터 가공하기: 연산자와 문자열', '기획팀에서 간단한 데이터 분석을 요청했습니다. 어제 하루 동안의 <span class=\'font-bold text-yellow-300\'>총 방문자 수(total_visits)가 1,250명</span>이고, <span class=\'font-bold text-yellow-300\'>유료 전환 사용자(paid_users)가 50명</span>일 때, \'유료 전환율(conversion_rate)\'이 몇 퍼센트인지 계산해서 출력해주세요.', 1, 'profKim', '2025-11-03 15:59:33'),
    (7, 3, '팀장 과업 지시', '흐름 제어: 조건과 반복으로 똑똑한 코드 만들기', '보안 강화의 첫 단계입니다. `user_role` 변수의 값에 따라 다른 환영 메시지를 보여주는 기능을 구현해야 합니다. 역할이 <span class=\'font-bold text-yellow-300\'>\'admin\'이면 \'관리자님 환영합니다.\'</span>를, <span class=\'font-bold text-yellow-300\'>\'editor\'이면 \'에디터님 안녕하세요.\'</span>를, 그 외의 <span class=\'font-bold text-yellow-300\'>모든 경우에는 \'환영합니다.\'</span>를 출력해주세요.', 1, 'profKim', '2025-11-03 15:59:33'),
    (7, 4, '팀장 과업 지시', '코드 재사용의 시작: 함수 정의와 활용', '여러 곳에서 사용될 환영 메시지를 매번 복사 붙여넣기 하는 대신, <span class=\'font-bold text-yellow-300\'>재사용 가능한 코드 덩어리</span>로 만들려고 합니다. \"Welcome to LogiCore Tech!\"를 출력하는 <span class=\'font-bold text-yellow-300\'>`show_welcome_message` 함수를 정의하고, 이 함수를 호출</span>해주세요.', 1, 'profKim', '2025-11-03 15:59:33'),
    (7, 5, '팀장 과업 지시', '자료구조 (1): 순서가 있는 데이터 묶음, 리스트와 튜플', '다음 스프린트에서 진행할 업무 목록을 관리해야 합니다. 먼저 <span class=\'font-bold text-yellow-300\'>`sprint_tasks` 라는 이름의 비어있는 리스트</span>를 하나 만들어주세요. 그 다음, 목록에 <span class=\'font-bold text-yellow-300\'>\'사용자 로그인 기능 개발\'</span>과 <span class=\'font-bold text-yellow-300\'>\'게시판 UI 개선\'</span>이라는 두 가지 업무를 추가해주세요.', 1, 'profKim', '2025-11-03 15:59:33'),
    (7, 6, '팀장 과업 지시', '자료구조 (2): Key-Value 데이터, 딕셔너리와 집합', '지금까지 사용자 정보를 개별 변수로 관리했는데, 한계가 명확하네요. <span class=\'font-bold text-yellow-300\'>한 명의 사용자 프로필 정보</span>(\'username\': \'rookie\', \'level\': 1, \'team\': \'솔루션개발팀\')를 하나의 묶음으로 관리해야 합니다. **\'딕셔너리(Dictionary)\'**를 사용하여 이 정보를 담은 `user_profile` 변수를 만들어주세요.', 1, 'profKim', '2025-11-03 15:59:33'),
    (7, 7, '팀장 과업 지시', '모듈화 및 중간 점검: 나만의 유틸리티 모듈 만들기', '다른 파일(`string_utils.py`)에 문자열을 뒤집는 `reverse_string` 함수가 정의되어 있다고 가정합니다. 현재 파일에서 <span class=\'font-bold text-yellow-300\'>`string_utils` 모듈을 불러오고(import)</span>, 이 모듈의 <span class=\'font-bold text-yellow-300\'>`reverse_string` 함수를 호출</span>하여 \"Hello\" 문자열을 뒤집은 결과를 `reversed_text` 변수에 저장해주세요.', 1, 'profKim', '2025-11-03 15:59:33'),
    (7, 8, '팀장 과업 지시', '객체 지향 프로그래밍 (1): 클래스와 객체의 이해', '사용자 데이터를 보다 체계적으로 관리하기 위해 <span class=\'font-bold text-yellow-300\'>\'객체 지향 프로그래밍\'</span> 개념을 도입하려고 합니다. 먼저, 사용자를 나타내는 설계도인 <span class=\'font-bold text-yellow-300\'>`User` 클래스를 정의</span>하고, 이 설계도를 바탕으로 실제 사용자 객체 <span class=\'font-bold text-yellow-300\'>`user1`을 생성</span>해주세요. 지금은 빈 껍데기만 만들어도 됩니다.', 1, 'profKim', '2025-11-03 15:59:33'),
    (7, 9, '팀장 과업 지시', '객체 지향 프로그래밍 (2): 상속을 통한 코드 확장', '서비스에 특별 권한을 가진 \'관리자\'가 필요하게 되었습니다. 관리자는 \'사용자\'의 속성(이름, 이메일)을 그대로 가지면서, 추가로 <span class=\'font-bold text-yellow-300\'>\'관리 등급(admin_level)\'</span> 속성을 가져야 합니다. <span class=\'font-bold text-yellow-300\'>상속(Inheritance)</span>을 사용하여 `User` 클래스를 확장한 `Admin` 클래스를 만들어주세요.', 1, 'profKim', '2025-11-03 15:59:33'),
    (7, 10, '팀장 과업 지시', '파일 처리와 예외 관리: 데이터 영구 저장 및 오류 대응', '서버 이벤트를 파일에 기록해야 합니다. <span class=\'font-bold text-yellow-300\'>`log_message` 내용을 `server.log` 파일에 새로 쓰는(write)</span> 코드를 작성해주세요. 그리고 기록 확인을 위해, <span class=\'font-bold text-yellow-300\'>파일 전체 내용을 다시 읽어서(read)</span> `content` 변수에 저장해야 합니다. <span class=\'font-bold text-yellow-300\'>`with open()` 구문</span>을 사용하세요.', 1, 'profKim', '2025-11-03 15:59:33'),
    (7, 11, '팀장 과업 지시', '파이썬 생태계 첫걸음: 표준 라이브러리와 외부 패키지', '이전 백업 스크립트의 의존성 문제를 해결하기 위해, 파이썬 <span class=\'font-bold text-yellow-300\'>표준 라이브러리 `zipfile`</span>을 사용하도록 코드를 개선합니다. <span class=\'font-bold text-yellow-300\'>`zipfile.ZipFile`</span>을 사용하여 `backup.zip` 파일을 열고, `important_data.txt` 파일을 이 <span class=\'font-bold text-yellow-300\'>ZIP 아카이브에 추가</span>하는 코드를 작성해주세요. `with` 구문을 사용해야 합니다.', 1, 'profKim', '2025-11-03 15:59:33'),
    (7, 12, '팀장 과업 지시', '최종 프로젝트: 주소록 관리 프로그램 제작', '마지막 과제입니다! <span class=\'font-bold text-yellow-300\'>연락처를 추가하고 볼 수 있는</span> 간단한 \'명령줄 주소록 프로그램\'을 만들려고 합니다. 이번 단계에서는 코딩 대신, 이 프로그램의 <span class=\'font-bold text-yellow-300\'>기능 목록, 데이터 저장 방식(클래스/변수 구조), 데이터 영속성(파일 저장) 방안, 사용자 인터페이스 흐름</span> 등을 포함한 구체적인 \'설계\' 문서를 작성해주세요.', 1, 'profKim', '2025-11-03 15:59:33');

INSERT INTO `TBL_USER`
(`ROLE`, `NAME`, `EMAIL`, `PASSWORD_HASH`, `STUDENT_NUM`, `STATUS`, `TERMS_AGREED`, `PRIVACY_AGREED`, `MARKETING_AGREED`, `MUST_CHANGE_PASSWORD`, `CREATE_DT`, `UPDATE_DT`)
VALUES
    ('PROFESSOR', '김원탁', 'wt0604@naver.com', '$2a$10$OZ.ecVdfxXNT2FAnKmDdbu/1Kb6hEwzAkk4i39AyIzIh0sOLpRIP.', '232323232', NULL, NULL, NULL, NULL, 0, '2025-10-31 14:45:46', '2025-10-31 14:45:46'),
    ('ADMIN', '오태훈', 'dhxogns920@naver.com', '$2a$10$OZ.ecVdfxXNT2FAnKmDdbu/1Kb6hEwzAkk4i39AyIzIh0sOLpRIP.', '9999999999999', 0, NULL, NULL, NULL, 0, '2025-10-31 14:45:46', '2025-10-31 14:45:46'),
    ('ADMIN', '관리자', 'dhxogns920@hyperwise.co.kr', '$2a$10$qey3WjqSF12us0gyErRaiuPj2mpUNqvqrvUi8tB2iKO6L.', '9999999999', 0, NULL, NULL, NULL, 0, '2025-11-04 13:58:13', '2025-11-04 13:58:13');